uint16 SMART_CAR_COMMAND_ENABLE=1
uint16 SMART_CAR_COMMAND_DISABLE=2
uint16 SMART_CAR_COMMAND_STOP=3
uint16 SMART_CAR_COMMAND_RECENTER_SERVO=4
uint16 SMART_CAR_COMMAND_GYRO_CAL=5
uint16 SMART_CAR_COMMAND_CLEAR_FAULTS=6
uint16 SMART_CAR_COMMAND_START_CURVATURE_CAL_POINT=7
uint16 SMART_CAR_COMMAND_START_CURVATURE_CAL_LEFT=8
uint16 SMART_CAR_COMMAND_START_CURVATURE_CAL_RIGHT=9
uint16 SMART_CAR_COMMAND_STOP_CURVATURE_CAL=10
uint16 SMART_CAR_COMMAND_FIREWATER_OFF=11

uint16 command
float32 param1
float32 param2
float32 param3
float32 param4
---
bool accepted
string message
